// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdewyfpqmcljdwutzmnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZXd5ZnBxbWNsamR3dXR6bW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODc3NzMsImV4cCI6MjA2MjU2Mzc3M30.CdYi_HKQCkcDlKr2cdpCZ8-q1kVmUgAYJjy1pL9ms4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);